
modLoader="javafml" 
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="soufmod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Souf mod" #mandatory

#updateJSONURL="https://change.me.example.invalid/updates.json" #optional

#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional

logoFile="examplemod.png" #optional

credits="Thanks for this example mod goes to Java" #optional

authors="Souf" #optional

description='''
Souf's description
'''
[[dependencies.soufmod]] 
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.soufmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
